import "./chunk-VHAA22YE.js";
import {
  PROTOCOL_ANALYTICS,
  PROTOCOL_CONTRIBUTE,
  PROTOCOL_DND,
  PROTOCOL_EDITOR,
  PROTOCOL_FEED,
  PROTOCOL_FETCH,
  PROTOCOL_IPC,
  PROTOCOL_LAUNCH,
  PROTOCOL_LLM,
  PROTOCOL_SECRETS,
  PROTOCOL_SETTINGS,
  PROTOCOL_SPACES,
  PROTOCOL_TASK,
  PROTOCOL_THEME,
  PROTOCOL_VCS
} from "./generated/protocol";
const PREFIX = "protocol-";
const schemeOf = (name) => name.slice(PREFIX.length);
const SCHEMES = {
  [PROTOCOL_ANALYTICS]: schemeOf(PROTOCOL_ANALYTICS),
  [PROTOCOL_CONTRIBUTE]: schemeOf(PROTOCOL_CONTRIBUTE),
  [PROTOCOL_DND]: schemeOf(PROTOCOL_DND),
  [PROTOCOL_EDITOR]: schemeOf(PROTOCOL_EDITOR),
  [PROTOCOL_FEED]: schemeOf(PROTOCOL_FEED),
  [PROTOCOL_FETCH]: schemeOf(PROTOCOL_FETCH),
  [PROTOCOL_IPC]: schemeOf(PROTOCOL_IPC),
  [PROTOCOL_LAUNCH]: schemeOf(PROTOCOL_LAUNCH),
  [PROTOCOL_LLM]: schemeOf(PROTOCOL_LLM),
  [PROTOCOL_SECRETS]: schemeOf(PROTOCOL_SECRETS),
  [PROTOCOL_SETTINGS]: schemeOf(PROTOCOL_SETTINGS),
  [PROTOCOL_SPACES]: schemeOf(PROTOCOL_SPACES),
  [PROTOCOL_TASK]: schemeOf(PROTOCOL_TASK),
  [PROTOCOL_THEME]: schemeOf(PROTOCOL_THEME),
  [PROTOCOL_VCS]: schemeOf(PROTOCOL_VCS)
};
export {
  SCHEMES
};
//# sourceMappingURL=protocolSchemes.js.map