// PROTOTYPE generator — one capability-descriptor set → three projections.
//
// Demonstrates §3 of docs/specs/SDK_SIMPLIFICATION_SPEC.md: from the SINGLE source
// (descriptors.spaces.mjs) we emit
//   (1) the typed wrappers .ts (the human / authoring-agent surface)
//   (2) the generated error-code unions + named types (from json-schema)
//   (3) the llms.txt fragment (the doc surface)
// The catalog (the embedded-agent surface) is already host-derived from the same
// names, so it is shown as a manifest rather than re-emitted.
//
// Run: node scripts/codegen-prototype/generate.mjs
//
// Deliberately dependency-free: it ships a tiny json-schema→TS good enough for the
// shapes the spaces family uses (object/enum/string/number/boolean/array/$ref/void).
// In the real impl this step is `json-schema-to-typescript`.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { family } from './descriptors.spaces.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, 'generated');

// ── tiny json-schema → TS type ────────────────────────────────────────────────
function tsType(schema) {
  if (!schema) return 'void';
  if (schema.$ref) return schema.$ref;
  switch (schema.type) {
    case 'void':
      return 'void';
    case 'string':
      return Array.isArray(schema.enum)
        ? schema.enum.map((v) => JSON.stringify(v)).join(' | ')
        : 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      return `${tsType(schema.items)}[]`;
    case 'object': {
      const props = schema.properties ?? {};
      const required = new Set(schema.required ?? []);
      const lines = Object.entries(props).map(([k, v]) => {
        const opt = required.has(k) ? '' : '?';
        return `  ${k}${opt}: ${tsType(v)};`;
      });
      return lines.length ? `{\n${lines.join('\n')}\n}` : 'Record<string, never>';
    }
    default:
      return 'unknown';
  }
}

// A named-interface emission (for the shared `types` table).
function emitNamedType(name, def) {
  const { schema, description } = def;
  const doc = description ? `/** ${description} */\n` : '';
  if (schema.type === 'object') {
    const props = schema.properties ?? {};
    const required = new Set(schema.required ?? []);
    const lines = Object.entries(props).map(([k, v]) => {
      const opt = required.has(k) ? '' : '?';
      const fieldDoc = v.description ? `  /** ${v.description} */\n` : '';
      return `${fieldDoc}  ${k}${opt}: ${tsType(v)};`;
    });
    return `${doc}export interface ${name} {\n${lines.join('\n')}\n}`;
  }
  // alias type (e.g. Role)
  return `${doc}export type ${name} = ${tsType(schema)};`;
}

const errUnionName = (m) =>
  m.alias.fn.replace(/^(\w)/, (c) => c.toUpperCase()) + 'Error';

// JSDoc block for a method.
function jsdoc(m) {
  const lines = [];
  lines.push('/**');
  for (const l of wrap(m.doc, 74)) lines.push(` * ${l}`);
  lines.push(' *');
  lines.push(` * Capability: \`${m.capability}\`. Catalog name: \`${m.name}\`.`);
  lines.push(
    ` * @throws \`Error & { code: ${errUnionName(m)} }\` on host refusal.`,
  );
  lines.push(' */');
  return lines.join('\n');
}

function wrap(text, width) {
  const words = text.split(/\s+/);
  const out = [];
  let line = '';
  for (const w of words) {
    if ((line + ' ' + w).trim().length > width) {
      out.push(line.trim());
      line = w;
    } else {
      line += ' ' + w;
    }
  }
  if (line.trim()) out.push(line.trim());
  return out;
}

// ── (1)+(2) the typed wrappers + types ────────────────────────────────────────
function emitWrappers() {
  const out = [];
  out.push('// GENERATED by scripts/codegen-prototype/generate.mjs — DO NOT EDIT.');
  out.push('// Source of truth: scripts/codegen-prototype/descriptors.spaces.mjs');
  out.push(`// Family: ${family.scheme} — ${family.doc.split('.')[0]}.`);
  out.push('');
  out.push("import { invoke } from '../../../src/catalog';");
  out.push('');

  // shared named types
  for (const [name, def] of Object.entries(family.types)) {
    out.push(emitNamedType(name, def));
    out.push('');
  }

  for (const m of family.methods) {
    out.push(`export type ${errUnionName(m)} =`);
    out.push('  ' + m.errors.map((e) => JSON.stringify(e)).join(' | ') + ';');
    out.push('');

    const paramsType = tsType(m.params);
    const resultType = tsType(m.result);
    const hasParams = m.params.type === 'object' && Object.keys(m.params.properties ?? {}).length > 0;
    const fn = m.alias.fn;
    const positional = m.alias.positional ?? [];

    out.push(jsdoc(m));

    // Positional alias form (preserves the existing hand-written signature exactly).
    if (positional.length && positional[0] !== 'opts') {
      const sigParams = positional
        .map((p) => `${p}: ${tsType(m.params.properties[p])}`)
        .join(', ');
      const objLit = `{ ${positional.join(', ')} }`;
      const call = `invoke<${resultType === 'void' ? 'void' : resultType}>(${JSON.stringify(m.name)}, ${objLit})`;
      out.push(
        resultType === 'void'
          ? `export const ${fn} = async (${sigParams}): Promise<void> => { await ${call}; };`
          : `export const ${fn} = (${sigParams}): Promise<${resultType}> =>\n  ${call};`,
      );
    } else if (positional[0] === 'opts') {
      // single optional opts object (listSpaces)
      const call = `invoke<${resultType}>(${JSON.stringify(m.name)}, opts)`;
      out.push(
        `export const ${fn} = (opts: ${paramsType} = {}): Promise<${resultType}> =>\n  ${call};`,
      );
    } else {
      // no params (listAllSpaces, listGrants)
      const call = `invoke<${resultType}>(${JSON.stringify(m.name)}, {})`;
      out.push(`export const ${fn} = (): Promise<${resultType}> =>\n  ${call};`);
    }
    out.push('');
  }
  return out.join('\n');
}

// ── (3) llms.txt fragment ─────────────────────────────────────────────────────
function emitLlmsTxt() {
  const out = [];
  out.push(`## spaces — ${family.doc}`);
  out.push('');
  out.push('| function | catalog name | capability | params | returns |');
  out.push('|---|---|---|---|---|');
  for (const m of family.methods) {
    const params = m.params.properties
      ? Object.keys(m.params.properties).join(', ') || '—'
      : '—';
    const ret = tsType(m.result).replace(/\n/g, ' ').replace(/\s+/g, ' ');
    out.push(
      `| \`${m.alias.fn}\` | \`${m.name}\` | \`${m.capability}\` | ${params} | \`${ret}\` |`,
    );
  }
  out.push('');
  return out.join('\n');
}

// ── (catalog manifest, already host-derived) ──────────────────────────────────
function emitCatalogManifest() {
  return JSON.stringify(
    family.methods.map((m) => ({
      name: m.name,
      capability: m.capability,
      stream: m.kind === 'stream' ? true : undefined,
    })),
    null,
    2,
  );
}

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'spaces.generated.ts'), emitWrappers() + '\n');
writeFileSync(join(outDir, 'spaces.llms.txt'), emitLlmsTxt() + '\n');
writeFileSync(join(outDir, 'spaces.catalog.json'), emitCatalogManifest() + '\n');

console.log('Generated from 1 descriptor set:');
console.log('  generated/spaces.generated.ts   (typed wrappers + types + error unions)');
console.log('  generated/spaces.llms.txt       (doc projection)');
console.log('  generated/spaces.catalog.json   (catalog manifest — host-derived twin)');
console.log(`\n${family.methods.length} methods, ${Object.keys(family.types).length} shared types — one edit each.`);
