#!/usr/bin/env node
/*
 * Bake `SDK_VERSION` from package.json into `src/version.ts` (SP2-6, debt §5.2).
 * The handshake (`runtime.ts` → `sdkHandshake`) reports this to the host; a
 * hand-maintained constant drifted (0.4.0 vs a 0.8.0 package), misreporting the
 * live version. Runs as `prebuild`, so every build bakes the current version; the
 * generated file is committed so jest + consumers see it without a build, and
 * `version.test.ts` fails CI if it ever drifts from package.json.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const out = join(root, 'src', 'version.ts');
const body =
  `// GENERATED by scripts/gen-version.mjs from package.json — do not edit by hand.\n` +
  `// Regenerated on every build (prebuild); kept honest by version.test.ts.\n\n` +
  `/** This SDK's package version, baked from package.json at build (SP2-6). */\n` +
  `export const SDK_VERSION = '${version}';\n`;

// Only write when changed, so a no-op build doesn't dirty the tree.
let current = '';
try {
  current = readFileSync(out, 'utf8');
} catch {
  /* first run */
}
if (current !== body) {
  writeFileSync(out, body);
  console.log(`Baked SDK_VERSION='${version}' -> ${out}`);
} else {
  console.log(`SDK_VERSION already '${version}' — ${out} unchanged.`);
}
